<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to Junkfood-Analyzer Backend'), '<span class="zf-green">', '</span>') ?></h1>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Manage junkfoods') ?></h3>
            </div>
            <div class="panel-body">
                <p><a href="<?php echo $this->url('junkfood',
                        array('action'=>'index'));?>">List junkfoods</a></p>
                <p><a href="<?php echo $this->url('junkfood',
                        array('action'=>'add'));?>">Add new junkfood</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Manage ingredients') ?></h3>
            </div>
            <div class="panel-body">
                <p><a href="<?php echo $this->url('junkfood',
                        array('action'=>'index'));?>">List ingredients</a></p>
                <p><a href="<?php echo $this->url('junkfood',
                        array('action'=>'add'));?>">Add new ingredients</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Manage users') ?></h3>
            </div>
            <div class="panel-body">
                <p><a href="<?php echo $this->url('users',
                        array('action'=>'index'));?>">List users</a></p>
                <p><a href="<?php echo $this->url('users',
                        array('action'=>'add'));?>">Add new users</a></p>
            </div>
        </div>
    </div>
</div>
