<?php

$title = 'Add new user';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('users', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('userID'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('password'));
echo $this->formRow($form->get('isAdmin'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();