<?php
$title = 'My User';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('users', array('action'=>'add'));?>">Add new user</a>
</p>

<table class="table">
    <tr>
        <th>Name</th>
        <th>Admin</th>
        <th>Options</th>
    </tr>
    <?php foreach ($users as $user) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($user->name);?></td>
            <td><?php
                    if($user->isAdmin == true)
                        echo "YES";
                    else
                        echo "NO";
                ?>
            </td>
            <td>
                <a href="<?php echo $this->url('users',
                    array('action'=>'edit', 'id' => $user->userID));?>">Edit</a> |
                <a href="<?php echo $this->url('users',
                    array('action'=>'delete', 'id' => $user->userID));?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>