<?php

$title = 'Add new ingredient';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('ingredient', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('ingrID')) . "<br>";
echo $this->formRow($form->get('ingrName')) . "<br>";
echo $this->formRow($form->get('kcalPer100g')) . "<br>";
echo $this->formRow($form->get('isVeggie')) . "<br>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();