<?php
$title = 'My Ingredient';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('ingredient', array('action'=>'add'));?>">Add new ingredient</a>
</p>

<table class="table">
    <tr>
        <th>Ingredient</th>
        <th>Kcal/100g</th>
        <th>Veggetable</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($ingredients as $ingredient) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($ingredient->ingrName);?></td>
            <td><?php echo $this->escapeHtml($ingredient->kcalPer100g);?></td>
            <td>
                <?php
                    if($ingredient->isVeggie == true)
                        echo "YES";
                    else
                        echo "NO";
                ?>
            </td>
            <td>
                <a href="<?php echo $this->url('ingredient',
                    array('action'=>'edit', 'id' => $ingredient->ingrID));?>">Edit </a>|
                <a href="<?php echo $this->url('ingredient',
                    array('action'=>'delete', 'id' => $ingredient->ingrID));?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>