<?php

$title = 'Add new junkfood';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('junkfood', array('action' => 'add')));
$form->prepare();
$form->types = $this->types;

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('junkfoodID'));
echo $this->formRow($form->get('name')) . "<br>";
echo $this->formRow($form->get('art')) . "<br>";
echo $this->formRow($form->get('kcal')) . "<br>";
echo $this->formRow($form->get('isVeggie')) . "<br>";
echo $this->formSubmit($form->get('submit')) . "<br>";
echo $this->form()->closeTag();