<div class="drogo row" style="padding-top: 20px; position: relative; width: 500px">
    <img style="display: block; width: 500px" src="<?php echo $this->basePath('img/khal-drogo.jpg') ?>">
    <span style="position: absolute; bottom: 0; background-color: silver;
    background-color: hsla(0, 0%, 100%, 0.5); width: 100%; font-size: 3em; text-align: center;">Khal Drogo empfielt: <br> <?php echo $food->art . ' ' . $food->name; ?><span>
</div>
