INSERT INTO `ingredients`(`ingrID`, `ingrName`, `kcalPer100g`, `isVeggie`) VALUES (1,"Mais (Bonduelle)",80,true);
INSERT INTO `ingredients`(`ingrID`, `ingrName`, `kcalPer100g`, `isVeggie`) VALUES (2,"Ananasstücke",68,true);
INSERT INTO `ingredients`(`ingrID`, `ingrName`, `kcalPer100g`, `isVeggie`) VALUES (3,"Rindersalami",432,false);
INSERT INTO `ingredients`(`ingrID`, `ingrName`, `kcalPer100g`, `isVeggie`) VALUES (4,"Chiliöl",822,true);
INSERT INTO `ingredients`(`ingrID`, `ingrName`, `kcalPer100g`, `isVeggie`) VALUES (5,"Zwiebel",28,true);
INSERT INTO `ingredients`(`ingrID`, `ingrName`, `kcalPer100g`, `isVeggie`) VALUES (6,"Parmesan",374,true);
INSERT INTO `ingredients`(`ingrID`, `ingrName`, `kcalPer100g`, `isVeggie`) VALUES (7,"Schinken (gekocht)",126,false);
INSERT INTO `ingredients`(`ingrID`, `ingrName`, `kcalPer100g`, `isVeggie`) VALUES (8,"Schinken (geräuchert)",136,false);
INSERT INTO `ingredients`(`ingrID`, `ingrName`, `kcalPer100g`, `isVeggie`) VALUES (9,"Mozarella",263,true);
INSERT INTO `ingredients`(`ingrID`, `ingrName`, `kcalPer100g`, `isVeggie`) VALUES (10,"Pepperoni",21,true);
INSERT INTO `ingredients`(`ingrID`, `ingrName`, `kcalPer100g`, `isVeggie`) VALUES (11,"Paprika (rot)",38,true);
INSERT INTO `ingredients`(`ingrID`, `ingrName`, `kcalPer100g`, `isVeggie`) VALUES (12,"Thunfisch",91,false);
INSERT INTO `ingredients`(`ingrID`, `ingrName`, `kcalPer100g`, `isVeggie`) VALUES (13,"Parmaschinken",250,false);
INSERT INTO `ingredients`(`ingrID`, `ingrName`, `kcalPer100g`, `isVeggie`) VALUES (14,"Cocktailtomaten",19,true);
INSERT INTO `ingredients`(`ingrID`, `ingrName`, `kcalPer100g`, `isVeggie`) VALUES (15,"Champignons",16,true);
INSERT INTO `ingredients`(`ingrID`, `ingrName`, `kcalPer100g`, `isVeggie`) VALUES (16,"Gorgonzola",358,true);
INSERT INTO `ingredients`(`ingrID`, `ingrName`, `kcalPer100g`, `isVeggie`) VALUES (17,"Ruccola",18,true);
INSERT INTO `ingredients`(`ingrID`, `ingrName`, `kcalPer100g`, `isVeggie`) VALUES (18,"Putenschinken",100,false);
INSERT INTO `ingredients`(`ingrID`, `ingrName`, `kcalPer100g`, `isVeggie`) VALUES (19,"Creme fraiche",294,true);
INSERT INTO `ingredients`(`ingrID`, `ingrName`, `kcalPer100g`, `isVeggie`) VALUES (20,"Salami (scharf)",375,false);